---
title: "world_map_plots"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(ggplot2)              
library(tidyverse)            
```

## R Markdown


```{r world happiness}
world_happiness <- readr::read_csv("https://raw.githubusercontent.com/illinois-stat447/fa21-prj-shiyuan8-sw20-zihanz12-zl32/master/data/world-happiness-report-2020.csv?token=AKH4K3ZTOOQABV5NEUJJGQLBXJOCQ")

world_happiness$region = world_happiness$`Country name`

world_happiness = world_happiness |>
  mutate(region = replace(region, region == 'USA', 'United States'))

world_happiness = world_happiness |>
  mutate(region = replace(region, region == 'Democratic Republic of the Congo', 'Democratic Republic of Congo'))

world_happiness = world_happiness |>
  mutate(region = replace(region, region == 'UK', 'United Kingdom'))

world_happiness = world_happiness |>
  mutate(region = replace(region, region == 'Greenland', 'Denmark'))


mapdata <- map_data("world") ##ggplot2
# View(mapdata)

new_mapdata = mapdata |>
  mutate(region = replace(region, region == 'USA', 'United States'))

new_mapdata = new_mapdata |>
  mutate(region = replace(region, region == 'Democratic Republic of the Congo', 'Democratic Republic of Congo'))

new_mapdata = new_mapdata |>
  mutate(region = replace(region, region == 'UK', 'United Kingdom'))

new_mapdata = new_mapdata |>
  mutate(region = replace(region, region == 'Greenland', 'Denmark'))


mapdata_world_happiness <- left_join(new_mapdata, world_happiness, by="region")
# View(mapdata)

#remove na
# mapdata1<-mapdata |> filter(!is.na(mapdata$`Ladder score`))
# View(mapdata1)

map1<-ggplot(mapdata_world_happiness, aes( x = long, y = lat, group=group)) +
  geom_polygon(aes(fill = `Ladder score`), color = "black")

map2 <- map1 + scale_fill_gradient(name = "Ladder score", low = "yellow", high =  "red", na.value = "grey50")+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        rect = element_blank())
map2

```


```{r covid}
covid_data_2020 = readr::read_csv("https://raw.githubusercontent.com/illinois-stat447/fa21-prj-shiyuan8-sw20-zihanz12-zl32/master/data/covid_2020_total.csv?token=AKH4K33CEG4UJXXTNV7LLFLBXJTT2")
#remove first index column
covid_data_2020 <- covid_data_2020[ -c(1) ]
# View(covid_data_2020)
covid_data_2020$region = covid_data_2020$`country`

mapdata <- map_data("world") ##ggplot2
# View(mapdata)

new_mapdata = mapdata |>
  mutate(region = replace(region, region == 'USA', 'United States'))

new_mapdata = new_mapdata |>
  mutate(region = replace(region, region == 'Democratic Republic of the Congo', 'Democratic Republic of Congo'))

new_mapdata = new_mapdata |>
  mutate(region = replace(region, region == 'UK', 'United Kingdom'))

new_mapdata = new_mapdata |>
  mutate(region = replace(region, region == 'Greenland', 'Denmark'))


# unique(new_mapdata[c("region")])

mapdata_and_covid_2020 <- left_join(new_mapdata, covid_data_2020, by="region")
# View(mapdata_and_covid_2020)



# View(unique(mapdata_and_covid_2020[c("region")]))

#remove na
# mapdata_and_covid_2020<-mapdata_and_covid_2020 |> filter(!is.na(mapdata_and_covid_2020$total_cases))
# View(mapdata_and_covid_2020)

map3<-ggplot(mapdata_and_covid_2020, aes( x = long, y = lat, group=group)) +
  geom_polygon(aes(fill = total_cases), color = "black")

map4 <- map3 + scale_fill_gradient(name = "total_cases", low = "light blue", high =  "dodgerblue4", na.value = "grey50")+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        rect = element_blank())
map4


map5<-ggplot(mapdata_and_covid_2020, aes( x = long, y = lat, group=group)) +
  geom_polygon(aes(fill = death_case_ratio), color = "black")

map6 <- map5 + scale_fill_gradient(name = "death_case_ratio", low = "light blue", high =  "dodgerblue4", na.value = "grey50")+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        rect = element_blank())
map6


# require(gridExtra)
# 
# grid.arrange(map6, map5, widths = c(10,10), ncol=2)
```





```{r vaccination}
vaccination_data_2020 <- readr::read_csv("https://raw.githubusercontent.com/illinois-stat447/fa21-prj-shiyuan8-sw20-zihanz12-zl32/master/vaccination/data/world_vacci_data_2020.csv?token=AKH4K37S6CBXCEW544XX6K3BXJ4CK")
vaccination_data_2020$region = vaccination_data_2020$`location`

mapdata_and_vaccination_2020 <- left_join(new_mapdata, vaccination_data_2020, by="region")

map5<-ggplot(mapdata_and_vaccination_2020, aes( x = long, y = lat, group=group)) +
  geom_polygon(aes(fill = people_vaccinated), color = "black")

map6 <- map5 + scale_fill_gradient(name = "people_vaccinated", low = "light blue", high =  "dodgerblue4", na.value = "grey50")+
  theme(axis.text.x = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks = element_blank(),
        axis.title.y=element_blank(),
        axis.title.x=element_blank(),
        rect = element_blank())
map6



```
```{r code}
world_happiness <- readr::read_csv("https://raw.githubusercontent.com/illinois-stat447/fa21-prj-shiyuan8-sw20-zihanz12-zl32/master/data/world-happiness-report-2020.csv?token=AKH4K3ZTOOQABV5NEUJJGQLBXJOCQ")

world_happiness$region = world_happiness$`Country name`

world_happiness = world_happiness |>
  mutate(region = replace(region, region == 'USA', 'United States'))

world_happiness = world_happiness |>
  mutate(region = replace(region, region == 'Democratic Republic of the Congo', 'Democratic Republic of Congo'))

world_happiness = world_happiness |>
  mutate(region = replace(region, region == 'UK', 'United Kingdom'))

world_happiness = world_happiness |>
  mutate(region = replace(region, region == 'Greenland', 'Denmark'))


covid_data_2020 = readr::read_csv("https://raw.githubusercontent.com/illinois-stat447/fa21-prj-shiyuan8-sw20-zihanz12-zl32/master/data/covid_2020_total.csv?token=AKH4K33CEG4UJXXTNV7LLFLBXJTT2")
#remove first index column
covid_data_2020 <- covid_data_2020[ -c(1) ]
# View(covid_data_2020)
covid_data_2020$region = covid_data_2020$`country`


vaccination_data_2020 <- readr::read_csv("https://raw.githubusercontent.com/illinois-stat447/fa21-prj-shiyuan8-sw20-zihanz12-zl32/master/vaccination/data/world_vacci_data_2020.csv?token=AKH4K37S6CBXCEW544XX6K3BXJ4CK")
vaccination_data_2020$region = vaccination_data_2020$`location`


covid_world_happiness <- left_join(world_happiness, covid_data_2020, by="region")
vaccination_covid_world_happiness_2020 <- left_join(covid_world_happiness, vaccination_data_2020, by="region")
vaccination_covid_world_happiness_2020

# write.csv(vaccination_covid_world_happiness_2020,"/cloud/project/vaccination_covid_world_happiness_2020.csv")
```

```{r}
# head(vaccination_covid_world_happiness_2020)

fit1 <- aov(`Ladder score` ~ `Generosity`+ `Perceptions of corruption`+ `total_cases` +`total_deaths` +`people_fully_vaccinated_per_hundred`+`total_cases_per_100k`+ `total_deaths_per_100k`+ `death_case_ratio` + `people_vaccinated` + `people_fully_vaccinated` + `people_vaccinated_per_hundred`+ `Freedom to make life choices` +   + `Logged GDP per capita`+ `Social support`+ `Healthy life expectancy`, vaccination_covid_world_happiness_2020)

anova(fit1)
```